### ISSUE TITLE
Remove dependency on imagemagick

### ISSUE THREAD

**Issue by Toddler-Boy** [yamadapc/juce-visual-regressions#1]
You don't even need to save the new png. You create a component snapshot, load the comparison PNG into a different juce::Image, and then do the subtraction.

This would completely eliminate the dependency on imagemagick and make this tool completely stand-alone.

If you need help with that function let me know.

One could even save the new snapshot and the differences as separate images. Optionally, one could increase the contrast for the difference-image, so it's easier to see the visual changes (fringes, wrong alpha values, etc.)

**Comment by reFX-Mike** [comment]
One could even save the new snapshot and even save the differences as a separate image. Optionally one could increase the contrast for the difference image, so it's easier to see the visual changes (fringes, wrong alpha values, etc.)

**Comment by yamadapc** [comment]
Thanks! I'd certainly appreciate help.

I wonder how much it's worth to implement that functionality to get rid of the dependency though; as it stands it'd be quite easy to change the diffing algorithm or parameters, since it's just calling into imagemagick.

I understand how distribution gets harder though.

**Comment by Toddler-Boy** [comment]
It's around 10-15 lines of code, so IMO totally worth it. It also removes a barrier for newcomers. I find the installation of ImageMagick confusing. There are multiple different versions (I've counted 27 different ones for Windows alone), people have to make sure it's in their PATH, etc.

Plus, adding a comparison function allows other creative outputs, like a "heatmap" where identical pixels are dark-purple, and the bigger the difference, the more the colors shift into red/yellow, up to white.

**Comment by yamadapc** [comment]
I've implemented the comparison using JUCE facilities. So this project no longer requires image-magick.
